"""Service for building LLM-generated Markdown reports from scan findings."""

import asyncio

from app.core.config import settings
from app.core.errors import AppError
from app.schemas.finding import FindingRecord
from app.schemas.report import ReportMetrics
from app.services.openrouter_client import (
    AGENT_KEY_ATTR,
    RATE_LIMIT_BACKOFF_SECONDS,
    OpenRouterClient,
)


async def build_report_markdown(
    findings: list[FindingRecord], metrics: ReportMetrics, risk_score: float, repo_url: str
) -> str:
    """Generate a human-readable Markdown report using an LLM.

    Takes the top 20 ranked findings (or all if fewer than 20), along with
    computed metrics and risk score, and prompts an LLM to produce a comprehensive
    Markdown report.

    Args:
        findings: List of findings, assumed to be pre-ranked (most severe first).
        metrics: Computed report metrics (total_findings, by_severity, by_agent, files_affected).
        risk_score: Overall risk score for the repository.
        repo_url: GitHub repository URL.

    Returns:
        Markdown-formatted report string generated by the LLM.
    """
    # Take only top 20 findings
    top_findings = findings[:20]

    # Construct system prompt
    system_prompt = """You are a code quality analyst. Generate a comprehensive Markdown report 
summarizing the security, performance, complexity, duplication, and reliability findings 
for a GitHub repository. The report should be clear, actionable, and well-structured.

Include:
- An executive summary with the overall risk score
- Key metrics (total findings, breakdown by severity and agent, files affected)
- Detailed findings with severity, file paths, and descriptions
- Recommendations for remediation

Use proper Markdown formatting with headers, lists, and emphasis where appropriate."""

    # Construct user prompt with data
    findings_text = "\n\n".join(
        f"**{f.title}**\n"
        f"- Severity: {f.severity}\n"
        f"- Agent: {f.agent}\n"
        f"- File: {f.file_path or 'N/A'}\n"
        f"- Confidence: {f.confidence:.2f}\n"
        f"- Description: {f.description}"
        for f in top_findings
    )

    user_prompt = f"""Generate a code quality report for the following repository:

**Repository:** {repo_url}
**Overall Risk Score:** {risk_score:.1f}

**Metrics:**
- Total Findings: {metrics.total_findings}
- By Severity: {metrics.by_severity}
- By Agent: {metrics.by_agent}
- Files Affected: {metrics.files_affected}

**Top {len(top_findings)} Findings:**

{findings_text}

Please generate a comprehensive Markdown report based on this information."""

    # Call LLM, backing off and escalating to the fallback model on 429
    # (mirrors agent_factory.run_agent's retry cascade; no key fallback here
    # since only the specialist agents got a second key by design).
    api_key = getattr(settings, AGENT_KEY_ATTR["chatbot"]) or ""
    models = [settings.agent_llm_model, settings.agent_llm_model_fallback]
    last_error: AppError | None = None

    for model in models:
        client = OpenRouterClient(
            api_key=api_key, model=model, timeout_seconds=settings.agent_timeout_seconds
        )
        for attempt in range(settings.agent_max_retries + 1):
            try:
                return await client.complete(system=system_prompt, user=user_prompt)
            except AppError as exc:
                last_error = exc
                if exc.error_code == "LLM_RATE_LIMITED" and attempt < settings.agent_max_retries:
                    backoff = RATE_LIMIT_BACKOFF_SECONDS[
                        min(attempt, len(RATE_LIMIT_BACKOFF_SECONDS) - 1)
                    ]
                    await asyncio.sleep(backoff)
                    continue
                break  # non-rate-limit error, or retries exhausted: try next model

    raise last_error
